sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 14.17.5
before_install:
  - npm i -g npm@^6.14.0
before_script:
  - npm prune
script:
  - npm run test:once
after_success:
  - npm run sematic-release
